---
- hosts: all
  become: true
  roles:
    - { role: server, tags: ['server'] }
    - { role: vagrant_local, tags: ['server'] }
    - { role: geerlingguy.mysql, tags: ['database'] }
    - { role: geerlingguy.php, tags: ['php', 'fpm'] }
    - { role: geerlingguy.php-mysql, tags: ['php'] }
    - { role: geerlingguy.php-xdebug, tags: ['php'] }
    - { role: geerlingguy.composer, tags: ['php', 'composer'] }
